# 파일 읽는 경로 및 파일 명
load_dir: "./resources/2021-03-01.json"

# 파일 출력 경로 및 파일 명
save_dir: "./result/scores.json"

# 분석할 필드 명 기재
fields: ["doc_content"]

# 전처리 옵션 값 기재
# 1: 특수문자 제거, 2: 한글 이외에 모두 제거
preprocessing: 1

# 단어 출력 개수: 0 ~ N
# 0으로 설정할 시 모든 단어 출력
word_num: 10

# 단어 출력 방법
# 1: 단어 점수 기준 내림차순, 2: 단어 글자 기준 오름차순
word_order: 1